name: CI
on:
  push:
    branches:
      - develop
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  change-detection:
    name: 🔍 Change
    uses: ./.github/workflows/reusable-change-detection.yml

  tests:
    name: 🇨‌ Test
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-tests)
    uses: ./.github/workflows/reusable-cpp-ci.yml
    with:
      # do not try to build docs in test builds
      cmake-args: "-DBUILD_QDMI_DOCS=OFF -G Ninja"

  install:
    name: 📦 Install
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-tests)
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    steps:
      # check out the repository (including submodules and all history)
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      # set up ccache for faster C++ builds
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          prepend_symlinks_to_path: false
          override_cache_key: c++-tests-ubuntu-latest-install
      # set up mold as linker for faster C++ builds
      - name: Set up mold as linker
        uses: rui314/setup-mold@v1
      # make sure ninja is installed
      - name: Install Ninja
        run: pipx install ninja
      # configure CMake in the specified mode for QDMI installation, set the install-prefix
      - name: Configure CMake for QDMI Installation
        run: cmake -S . -B install-build -DCMAKE_BUILD_TYPE=Release
      # build the project in the specified mode
      - name: Build and Install QDMI
        run: cmake --build install-build --target install --prefix /my/install/prefix
      # configure CMake in the specified mode for using the installed QDMI
      - name: Configure CMake for use of installed QDMI
        run:
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DUSE_INSTALLED_QDMI=ON
          -DCMAKE_INSTALL_PREFIX=install-dir
      # build the project in the specified mode
      - name: Build QDMI examples, templates, and tests with installed QDMI
        run: cmake --build build
      # run the tests
      - name: Test
        run:
          ctest -C Release --output-on-failure --test-dir build --repeat until-pass:3 --timeout 600

  linter:
    name: 🇨‌ Lint
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-linter)
    uses: cda-tum/mqt-workflows/.github/workflows/reusable-cpp-linter.yml@v1.4
    with:
      clang-version: 19
      cpp-linter-extra-args: ""
      # do not try to build docs in linter builds
      cmake-args: "-DBUILD_QDMI_DOCS=OFF"

  code-ql:
    name: 📝 CodeQL
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-code-ql)
    uses: cda-tum/mqt-workflows/.github/workflows/reusable-code-ql-cpp.yml@v1.4
    with:
      # do not try to build docs in CodeQL builds
      cmake-args: "-DBUILD_QDMI_DOCS=OFF"

  docs:
    name: 📝 Build and Deploy Docs
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-docs)
    uses: ./.github/workflows/reusable-docs.yml
    permissions:
      contents: write

  required-checks-pass: # This job does nothing and is only used for branch protection
    name: 🚦 Check
    if: always()
    needs:
      - change-detection
      - tests
      - linter
      - code-ql
      - docs
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: >-
            ${{
              fromJSON(needs.change-detection.outputs.run-tests)
              && '' || 'tests,'
            }} ${{
              fromJSON(needs.change-detection.outputs.run-linter)
              && '' || 'linter,'
            }} ${{
              fromJSON(needs.change-detection.outputs.run-code-ql)
              && '' || 'code-ql,'
            }} ${{
              fromJSON(needs.change-detection.outputs.run-docs)
              && '' || 'docs,'
            }}
          jobs: ${{ toJSON(needs) }}
