name: Release Drafter

on:
  push:
    branches:
      - develop
      - v1.2.x

permissions: {}

jobs:
  update_release_draft:
    name: Run
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@eada3c96a64734dd381cfbda23511034e328ddb0 # v7.6.0
