name: Release Drafter

on:
  push:
    branches:
      - develop
      - v1.2.x

permissions: {}

jobs:
  update_release_draft:
    name: Run
    permissions:
      contents: write
    runs-on: ubuntu-26.04
    steps:
      - uses: release-drafter/release-drafter@978bb0b30c5ee8cdd332ced253758157150d43f0 # v7.10.0
