name: 🏗️ Build and Test Templates
on:
  workflow_call:

permissions:
  contents: read

jobs:
  device-template:
    name: Build Device Template
    runs-on: ubuntu-24.04
    env:
      CIBW_ENVIRONMENT_PASS_LINUX: CMAKE_ARGS
      CMAKE_ARGS: >-
        -DQDMI_REPO_OWNER=${{ github.event.pull_request.head.repo.owner.login || github.repository_owner }}
        -DQDMI_REV=${{ github.event.pull_request.head.sha || github.sha }}
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: qdmi
          persist-credentials: false
      - name: Configure template
        working-directory: qdmi
        run: >
          cmake -DQDMI_GENERATE_TEMPLATE=ON \
                -DTEMPLATE_PREFIX="MQSS" \
                -DTEMPLATE_PATH="$GITHUB_WORKSPACE" \
                -S . -B build
      - name: Generate template
        working-directory: qdmi
        run: cmake --build build --target qdmi-template
      - name: Delete source repository and build directory
        run: |
          rm -rf qdmi build
      - name: Initialize as git repository (with main as branch name) and commit
        run: |
          git config --global init.defaultBranch main
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git init
          git add .
          git commit -m "🎉 Initial commit"
      - name: Build template
        run: |
          cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_MQSS_QDMI_TESTS=ON $CMAKE_ARGS
          cmake --build build --config Release
      - name: Install Doxygen
        uses: ssciwr/doxygen-install@fa3e94d34131d3990b6b8ba939ab982964aa3758 # v2.0.3
        with:
          version: "1.15.0"
      - name: Build docs
        run: |
          cmake -G Ninja -S . -B build_docs -DCMAKE_BUILD_TYPE=Release -DBUILD_MQSS_QDMI_DOCS=ON -DBUILD_MQSS_QDMI_TESTS=OFF $CMAKE_ARGS
          cmake --build build_docs --config Release --target mqss_qdmi_device_docs
          rm -rf build_docs
      - uses: pypa/cibuildwheel@1828c10ab37f080699c7b81cea34097c684a7074 # v4.2.0
      - name: Verify clean directory
        run: git diff --exit-code
      - name: Upload wheels
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ github.event_name == 'pull_request' && 'dev-' || '' }}cibw-wheels-${{ runner.runs-on }}
          path: wheelhouse/*.whl
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
          save-cache: ${{ github.ref == 'refs/heads/main' }}
      - name: Build SDist
        run: uv build --sdist
      - name: Check metadata
        run: uvx twine check dist/*
      - name: Run check-sdist
        run: uvx check-sdist --inject-junk
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ github.event_name == 'pull_request' && 'dev-' || '' }}cibw-sdist
          path: dist/*.tar.gz
