name: 🇨‌ • CI
on:
  workflow_call:
    inputs:
      cmake-args:
        description: "Additional arguments to pass to CMake on every OS"
        default: ""
        type: string
      cmake-args-ubuntu:
        description: "Additional arguments to pass to CMake on Ubuntu"
        default: ""
        type: string
      cmake-args-macos:
        description: "Additional arguments to pass to CMake on macOS"
        default: ""
        type: string

jobs:
  cpp-tests-ubuntu:
    name: 🐧 ${{ matrix.config }}
    strategy:
      matrix:
        config: [Debug, Release]
      fail-fast: false
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-tests-ubuntu.yml@v1.8
    with:
      config: ${{ matrix.config }}
      cmake-args: ${{ inputs.cmake-args }} ${{ inputs.cmake-args-ubuntu }}

  cpp-tests-macos:
    name: 🍎
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-tests-macos.yml@v1.8
    with:
      cmake-args: ${{ inputs.cmake-args }} ${{ inputs.cmake-args-macos }}

  cpp-tests-install:
    name: 📦 Install
    uses: ./.github/workflows/reusable-cpp-install-tests.yml
    with:
      cmake-args: ${{ inputs.cmake-args }}

  coverage:
    name: 📈
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-coverage.yml@v1.8
    with:
      cmake-args: ${{ inputs.cmake-args }} ${{ inputs.cmake-args-ubuntu }}
    permissions:
      contents: read
      id-token: write
