name: 🇨‌ • CI
on:
  workflow_call:
    inputs:
      cmake-args:
        description: "Additional arguments to pass to CMake on every OS"
        default: ""
        type: string
      cmake-args-ubuntu:
        description: "Additional arguments to pass to CMake on Ubuntu"
        default: ""
        type: string
      cmake-args-macos:
        description: "Additional arguments to pass to CMake on macOS"
        default: ""
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  cpp-tests-ubuntu:
    name: 🐧 ${{ matrix.config }}
    strategy:
      matrix:
        config: [Debug, Release]
      fail-fast: false
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-tests-ubuntu.yml@99170045e26c2564e9573174b573310e211fca72 # v1.17.10
    with:
      config: ${{ matrix.config }}
      cmake-args: ${{ inputs.cmake-args }} ${{ inputs.cmake-args-ubuntu }}

  cpp-tests-macos:
    name: 🍎
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-tests-macos.yml@99170045e26c2564e9573174b573310e211fca72 # v1.17.10
    with:
      cmake-args: ${{ inputs.cmake-args }} ${{ inputs.cmake-args-macos }}

  cpp-tests-install:
    name: 📦 Install
    uses: ./.github/workflows/reusable-cpp-install-tests.yml
    with:
      cmake-args: ${{ inputs.cmake-args }}

  coverage:
    name: 📈
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install Ninja
        run: pipx install ninja
      - name: Configure CMake
        run: |
          cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON -DBUILD_QDMI_DOCS=OFF
      - name: Build
        run: cmake --build build --config Debug
      - name: Test
        run: ctest -C Debug --output-on-failure --test-dir build --repeat until-pass:3 --timeout 600
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          fail_ci_if_error: true
          flags: cpp
          use_oidc: true
