name: 🏗️ Build and Test Templates
on:
  workflow_call:

permissions:
  contents: read

jobs:
  device-template:
    name: Build Device Template
    runs-on: ubuntu-24.04
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          path: qdmi
      - name: Configure template
        working-directory: qdmi
        run: >
          cmake -DQDMI_GENERATE_TEMPLATE=ON \
                -DTEMPLATE_PREFIX="MQSS" \
                -DTEMPLATE_PATH="$GITHUB_WORKSPACE" \
                -S . -B build
      - name: Generate template
        working-directory: qdmi
        run: cmake --build build --target qdmi-template
      - name: Delete source repository and build directory
        run: |
          rm -rf qdmi build
      - name: Initialize as git repository (with main as branch name) and commit
        run: |
          git config --global init.defaultBranch main
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git init
          git add .
          git commit -m "🎉 Initial commit"
      - name: Build template
        run: |
          cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_MQSS_QDMI_TESTS=ON
          cmake --build build --config Release
      - name: Install Doxygen
        uses: ssciwr/doxygen-install@501e53b879da7648ab392ee226f5b90e42148449 # v1.6.4
        with:
          version: "1.15.0"
      - name: Build docs
        run: |
          cmake -G Ninja -S . -B build_docs -DCMAKE_BUILD_TYPE=Release -DBUILD_MQSS_QDMI_DOCS=ON -DBUILD_MQSS_QDMI_TESTS=OFF
          cmake --build build_docs --config Release --target mqss_qdmi_device_docs
          rm -rf build_docs
      - uses: pypa/cibuildwheel@63fd63b352a9a8bdcc24791c9dbee952ee9a8abc # v3.3.0
      - name: Verify clean directory
        run: git diff --exit-code
      - name: Upload wheels
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ github.event_name == 'pull_request' && 'dev-' || '' }}cibw-wheels-${{ runner.runs-on }}
          path: wheelhouse/*.whl
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          enable-cache: true
          save-cache: ${{ github.ref == 'refs/heads/main' }}
      - name: Build SDist
        run: uv build --sdist
      - name: Check metadata
        run: uvx twine check dist/*
      - name: Run check-sdist
        run: uvx check-sdist --inject-junk
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ github.event_name == 'pull_request' && 'dev-' || '' }}cibw-sdist
          path: dist/*.tar.gz
