var searchData=
[
  ['package_0',['Use an Installed Package',['../md_docs_2installation.html#use-an-installed-package',1,'']]],
  ['parameter_20required_1',['Breaking Change: Timeout Parameter Required',['../md_UPGRADING.html#breaking-change-timeout-parameter-required',1,'']]],
  ['parameters_20non_20breaking_2',['New Authentication Parameters (Non-Breaking)',['../md_UPGRADING.html#new-authentication-parameters-non-breaking',1,'']]],
  ['partially_20breaking_3',['Property Naming and New Properties (Partially Breaking)',['../md_UPGRADING.html#property-naming-and-new-properties-partially-breaking',1,'']]],
  ['participation_4',['Origins, Maintenance, and Participation',['../md_docs_2ecosystem.html#ecosystem-stewardship',1,'']]],
  ['placed_20in_20the_20constants_20h_20header_20and_20some_20are_20not_5',['Why are some enum definitions placed in the &lt;span class=&quot;tt&quot;&gt;constants.h&lt;/span&gt; header and some are not?',['../md_docs_2rationale.html#rationale-enum-definitions',1,'']]],
  ['point_6',['Choose a Starting Point',['../index.html#choose-a-starting-point',1,'']]],
  ['pointers_7',['Why does QDMI use opaque pointers?',['../md_docs_2rationale.html#rationale-opaque-pointers',1,'']]],
  ['prefix_8',['Why do device implementations use a prefix?',['../md_docs_2rationale.html#rationale-prefix',1,'']]],
  ['prefix_20handling_9',['Changes to Prefix Handling',['../md_UPGRADING.html#changes-to-prefix-handling',1,'']]],
  ['prefixes_20exported_20from_20device_20targets_10',['Stable device IDs and symbol prefixes exported from device targets',['../md_UPGRADING.html#stable-device-ids-and-symbol-prefixes-exported-from-device-targets',1,'']]],
  ['presets_11',['CMake presets',['../md_UPGRADING.html#cmake-presets',1,'']]],
  ['principles_12',['Core Principles',['../md_docs_2ai__usage.html#core-principles',1,'']]],
  ['program_13',['Does installing QDMI let me run a quantum program?',['../md_docs_2faq.html#does-installing-qdmi-let-me-run-a-quantum-program',1,'']]],
  ['program_20formats_20non_20breaking_14',['New Program Formats (Non-Breaking)',['../md_UPGRADING.html#new-program-formats-non-breaking',1,'']]],
  ['program_20jobs_15',['Multi-program jobs',['../md_UPGRADING.html#multi-program-jobs',1,'']]],
  ['programs_20and_20results_16',['Does every device support the same programs and results?',['../md_docs_2faq.html#does-every-device-support-the-same-programs-and-results',1,'']]],
  ['prohibited_20uses_17',['Prohibited Uses',['../md_docs_2ai__usage.html#prohibited-uses',1,'']]],
  ['project_18',['Creating a new Project',['../md_docs_2templates.html#template-create',1,'']]],
  ['properties_19',['Properties',['../md_docs_2examples.html#device-string',1,'Basic String Properties'],['../md_docs_2examples.html#device-complex',1,'Complex Properties'],['../md_UPGRADING.html#device-level-properties',1,'Device-Level Properties'],['../md_docs_2examples.html#device-int-enumeration',1,'Integer or Enumeration Properties'],['../md_docs_2examples.html#device-list',1,'List Properties'],['../md_UPGRADING.html#operation-level-properties',1,'Operation-Level Properties'],['../md_UPGRADING.html#site-level-properties',1,'Site-Level Properties']]],
  ['properties_20',['Optional queue properties',['../md_UPGRADING.html#optional-queue-properties',1,'']]],
  ['properties_20non_20breaking_21',['Properties Non Breaking',['../md_UPGRADING.html#neutral-atom-device-properties-non-breaking',1,'Neutral Atom Device Properties (Non-Breaking)'],['../md_UPGRADING.html#new-properties-non-breaking',1,'New Properties (Non-Breaking)']]],
  ['properties_20partially_20breaking_22',['Property Naming and New Properties (Partially Breaking)',['../md_UPGRADING.html#property-naming-and-new-properties-partially-breaking',1,'']]],
  ['property_23',['Why does QDMI not define individual functions for each property?',['../md_docs_2rationale.html#rationale-properties',1,'']]],
  ['property_20naming_20and_20new_20properties_20partially_20breaking_24',['Property Naming and New Properties (Partially Breaking)',['../md_UPGRADING.html#property-naming-and-new-properties-partially-breaking',1,'']]],
  ['property_20query_20and_20timeout_20breaking_20change_25',['Job Property Query and Timeout (Breaking Change)',['../md_UPGRADING.html#job-property-query-and-timeout-breaking-change',1,'']]],
  ['property_20query_20functions_20non_20breaking_26',['New Job Property Query Functions (Non-Breaking)',['../md_UPGRADING.html#new-job-property-query-functions-non-breaking',1,'']]],
  ['property_20rename_27',['Breaking Change: Property Rename',['../md_UPGRADING.html#breaking-change-property-rename',1,'']]],
  ['publications_28',['Publications',['../md_docs_2ecosystem.html#ecosystem-publications',1,'']]],
  ['pull_20request_20workflow_29',['Pull Request Workflow',['../md_docs_2contributing.html#pull-request-workflow',1,'']]],
  ['pulse_20metadata_30',['Pulse metadata',['../md_UPGRADING.html#pulse-metadata',1,'']]],
  ['python_31',['Python',['../md_docs_2faq.html#can-i-use-qdmi-from-python',1,'Can I use QDMI from Python?'],['../md_docs_2faq.html#why-is-it-written-in-c-and-not-in-python',1,'Why is it written in C and not in Python?']]],
  ['python_20support_32',['Python support',['../md_UPGRADING.html#python-support',1,'']]]
];
