var searchData=
[
  ['define_20individual_20functions_20for_20each_20property_0',['Why does QDMI not define individual functions for each property?',['../md_docs_2rationale.html#rationale-properties',1,'']]],
  ['definitions_20placed_20in_20the_20constants_20h_20header_20and_20some_20are_20not_1',['Why are some enum definitions placed in the &lt;span class=&quot;tt&quot;&gt;constants.h&lt;/span&gt; header and some are not?',['../md_docs_2rationale.html#rationale-enum-definitions',1,'']]],
  ['deployment_2',['Munich: Origins and Deployment',['../md_docs_2ecosystem.html#munich-origins-and-deployment',1,'']]],
  ['deployment_20responsibilities_3',['Deployment Responsibilities',['../md_docs_2ecosystem.html#ecosystem-operations',1,'']]],
  ['develops_20it_4',['Where is QDMI used, and who develops it?',['../md_docs_2faq.html#where-is-qdmi-used-and-who-develops-it',1,'']]],
  ['device_5',['Device',['../md_docs_2examples.html#device',1,'Implementing a Device'],['../md_docs_2getting__started.html#getting-started-runtime',1,'Move to a Simulator or External Device']]],
  ['device_20ids_6',['Replaceable QDMI drivers and stable device IDs',['../md_UPGRADING.html#replaceable-qdmi-drivers-and-stable-device-ids',1,'']]],
  ['device_20ids_20and_20symbol_20prefixes_20exported_20from_20device_20targets_7',['Stable device IDs and symbol prefixes exported from device targets',['../md_UPGRADING.html#stable-device-ids-and-symbol-prefixes-exported-from-device-targets',1,'']]],
  ['device_20implementations_8',['Required Changes for Device Implementations',['../md_UPGRADING.html#required-changes-for-device-implementations',1,'']]],
  ['device_20implementations_9',['New header for managing exported symbols of device implementations',['../md_UPGRADING.html#new-header-for-managing-exported-symbols-of-device-implementations',1,'']]],
  ['device_20implementations_20use_20a_20prefix_10',['Why do device implementations use a prefix?',['../md_docs_2rationale.html#rationale-prefix',1,'']]],
  ['device_20interface_11',['QDMI Device Interface',['../group__device__interface.html',1,'']]],
  ['device_20job_20interface_12',['QDMI Device Job Interface',['../group__device__job__interface.html',1,'']]],
  ['device_20level_20properties_13',['Device-Level Properties',['../md_UPGRADING.html#device-level-properties',1,'']]],
  ['device_20management_20interface_14',['Quantum Device Management Interface',['../index.html#quantum-device-management-interface',1,'']]],
  ['device_20properties_20non_20breaking_15',['Neutral Atom Device Properties (Non-Breaking)',['../md_UPGRADING.html#neutral-atom-device-properties-non-breaking',1,'']]],
  ['device_20query_20interface_16',['QDMI Device Query Interface',['../group__device__query__interface.html',1,'']]],
  ['device_20representations_20in_20a_20multicore_20architecture_17',['Child device representations in a multicore architecture',['../md_UPGRADING.html#child-device-representations-in-a-multicore-architecture',1,'']]],
  ['device_20session_20interface_18',['QDMI Device Session Interface',['../group__device__session__interface.html',1,'']]],
  ['device_20support_20the_20same_20programs_20and_20results_19',['Does every device support the same programs and results?',['../md_docs_2faq.html#does-every-device-support-the-same-programs-and-results',1,'']]],
  ['device_20targets_20',['Stable device IDs and symbol prefixes exported from device targets',['../md_UPGRADING.html#stable-device-ids-and-symbol-prefixes-exported-from-device-targets',1,'']]],
  ['device_20template_21',['device template',['../md_UPGRADING.html#updated-qdmi-device-template',1,'Updated QDMI device template'],['../md_UPGRADING.html#updated-qdmi-device-template-1',1,'Updated QDMI device template']]],
  ['device_2eh_22',['device.h',['../device_8h.html',1,'']]],
  ['devices_20against_20the_20qdmi_20header_20only_20library_23',['No need to link devices against the QDMI header-only library',['../md_UPGRADING.html#no-need-to-link-devices-against-the-qdmi-header-only-library',1,'']]],
  ['devices_20and_20clients_24',['Why are there separate kinds of jobs for devices and clients?',['../md_docs_2rationale.html#rationale-job-structs',1,'']]],
  ['devices_20have_20sessions_25',['Why do devices have sessions?',['../md_docs_2rationale.html#device-session',1,'']]],
  ['diagnose_20configuration_20and_20loading_20failures_26',['Diagnose Configuration and Loading Failures',['../md_docs_2getting__started.html#getting-started-diagnostics',1,'']]],
  ['different_20kinds_20of_20sites_27',['Why are there different kinds of sites?',['../md_docs_2rationale.html#rationale-site-types',1,'']]],
  ['disclosure_28',['4. Transparency and Disclosure',['../md_docs_2ai__usage.html#transparency-and-disclosure',1,'']]],
  ['discovery_20submission_20and_20results_29',['Verify Discovery, Submission, and Results',['../md_docs_2getting__started.html#getting-started-checkpoint',1,'']]],
  ['do_20device_20implementations_20use_20a_20prefix_30',['Why do device implementations use a prefix?',['../md_docs_2rationale.html#rationale-prefix',1,'']]],
  ['do_20devices_20have_20sessions_31',['Why do devices have sessions?',['../md_docs_2rationale.html#device-session',1,'']]],
  ['do_20i_20select_20compatible_20versions_32',['How do I select compatible versions?',['../md_docs_2faq.html#how-do-i-select-compatible-versions',1,'']]],
  ['do_20sessions_20need_20to_20be_20initialized_20after_20allocation_33',['Why do sessions need to be initialized after allocation?',['../md_docs_2rationale.html#rationale-session-init',1,'']]],
  ['documentation_34',['Documentation',['../md_docs_2contributing.html#building-the-documentation',1,'Building the Documentation'],['../md_docs_2contributing.html#working-on-the-documentation',1,'Working on the Documentation']]],
  ['does_20every_20device_20support_20the_20same_20programs_20and_20results_35',['Does every device support the same programs and results?',['../md_docs_2faq.html#does-every-device-support-the-same-programs-and-results',1,'']]],
  ['does_20installing_20qdmi_20let_20me_20run_20a_20quantum_20program_36',['Does installing QDMI let me run a quantum program?',['../md_docs_2faq.html#does-installing-qdmi-let-me-run-a-quantum-program',1,'']]],
  ['does_20qdmi_20not_20define_20individual_20functions_20for_20each_20property_37',['Why does QDMI not define individual functions for each property?',['../md_docs_2rationale.html#rationale-properties',1,'']]],
  ['does_20qdmi_20use_20opaque_20pointers_38',['Why does QDMI use opaque pointers?',['../md_docs_2rationale.html#rationale-opaque-pointers',1,'']]],
  ['driver_39',['Implementing a QDMI Driver',['../md_docs_2examples.html#driver',1,'']]],
  ['drivers_20and_20stable_20device_20ids_40',['Replaceable QDMI drivers and stable device IDs',['../md_UPGRADING.html#replaceable-qdmi-drivers-and-stable-device-ids',1,'']]],
  ['duration_20breaking_20change_41',['Units for Length and Duration (Breaking Change)',['../md_UPGRADING.html#units-for-length-and-duration-breaking-change',1,'']]],
  ['dynamic_20content_42',['Dynamic Content',['../md_docs_2contributing.html#dynamic-content',1,'']]]
];
